// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxjuvxaryrkkyxpvljcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4anV2eGFyeXJra3l4cHZsamNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjYyOTEsImV4cCI6MjA1NzgwMjI5MX0.OH7y5HKIt7jbZiHVQvYFLdYmIss8ttNnrePR-AB_13Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);